server:
  tomcat:
    max-http-form-post-size: 40MB
  port: 8180
  servlet:
    session:
      timeout: 3600s

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true